project_id = "gehhaudrxqitxbzkuapg"

[functions.create-demo-accounts]
verify_jwt = false

[functions.populate-taxonomy]
verify_jwt = false

[functions.seed-construction-questions]
verify_jwt = false

[functions.seed-carpentry-questions]
verify_jwt = false

[functions.seed-electrical-questions]
verify_jwt = false