project_id = "gehhaudrxqitxbzkuapg"

[functions.create-demo-accounts]
verify_jwt = false

[functions.populate-taxonomy]
verify_jwt = false

[functions.seed-construction-questions]
verify_jwt = false

[functions.seed-carpentry-questions]
verify_jwt = false

[functions.seed-electrical-questions]
verify_jwt = false

[functions.seed-pool-spa-questions]
verify_jwt = false

[functions.seed-hvac-questions]
verify_jwt = false

[functions.seed-painting-decorating-questions]
verify_jwt = false

[functions.seed-gardening-landscaping-questions]
verify_jwt = false

[functions.seed-kitchen-bathroom-questions]
verify_jwt = false

[functions.seed-floors-doors-windows-questions]
verify_jwt = false

[functions.seed-handyman-questions]
verify_jwt = false

[functions.create-custom-demo]
verify_jwt = false
