project_id = "kcncrtayycwdwrxcgler"

[functions.ai-chatbot]
verify_jwt = true

[functions.generate-questions]
verify_jwt = false

[functions.estimate-price]
verify_jwt = false

[functions.extract-image-text]
verify_jwt = true

[functions.generate-job-description]
verify_jwt = true
